version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PIP_NO_CACHE_DIR=1
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
